### ISSUE TITLE
Early wrapper creation breaks ruby compile on image build

### ISSUE THREAD

**Issue by floze** [phusion/passenger-docker#170] opened 2017-02-20 00:37 UTC
Hi,

I've stumbled upon this when I built the image for the raspberry pi (armhf) and had to compile ruby from source, as there dont seem to be any binaries yet.

Having this "ghostly" wrapper created beforehand (i.e. before rvm installs/compiles any ruby at all) it breaks the configure part of the ruby compilation:

https://github.com/phusion/passenger-docker/blob/8d0679bf1e8b615c99e14cdbed04d8882cf0e89c/image/ruby_support/prepare.sh#L25

The rvm installer later on seems to check on whether ruby is present or not in /usr/bin and then calls itself indefinitely, by means of the wrapper above.

**Comment by dmitrym0** [comment] 2017-03-01 21:01
This sounds like a duplicate of #169. Do you have a workaround?

**Comment by floze** [comment] 2017-03-02 17:10
I moved the wrapper creation from `image/ruby_support/prepare.sh` to `image/ruby_support/finalize.sh` on my fork, as can be seen here <https://github.com/floze/raspbian-passenger/blob/02334a17faf8e86b1957300b362d11a8930cea63/image/ruby_support/finalize.sh>

This only affected me during the build process. The workaround above let me build the image in the end, although I'm not sure if this would resolve #169, since an incorrect wrapper could still go rogue I suppose.

**Closed** 2017-05-18 14:19 UTC
