### ISSUE TITLE
Passenger docker builds failing in CI. 

### ISSUE THREAD

**Issue by prdanelli** [phusion/passenger-docker#324] opened 2021-09-30 21:33 UTC
Hello, we're using `phusion/passenger-ruby27:1.0.12` for our production releases and as of sometime this afternoon all builds are failing with the following error: 

```
E: The repository 'https://oss-binaries.phusionpassenger.com/apt/passenger focal Release' does not have a Release file.error building image: error building stage: failed to execute command: waiting for process to exit: exit status 100
ERROR: Job failed: command terminated with exit code 1
```
We had a successful build at 11:03pm BST (GMT+1), but then when i retried that same build again at 16:10 BST the previously working build was giving the same error. I've just tried again now, incase it was something temporary (22:30 BST) and the builds are still failing.

The focal releases seem available, so i'm really not sure what might be happening. 

The Dockerfile for this is as follows (just so you can see exactly what we're doing - nothing special)...

```docker
FROM phusion/passenger-ruby27:1.0.12

RUN apt-get update -qq && \
    apt-get install -y \
                       build-essential \
                       ghostscript \
                       imagemagick \
                       libpq-dev \
                       nodejs \
                       libreoffice \
                       libsasl2-dev \
                       netcat \
                       postgresql-client \
                       rsync \
                       tzdata \
                       unzip \
                       ffmpeg \
                       && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# If changes are made to fits version or location,
# amend `LD_LIBRARY_PATH` in docker-compose.yml accordingly.
RUN mkdir -p /opt/fits && \
    curl -fSL -o /opt/fits/fits-latest.zip https://projects.iq.harvard.edu/files/fits/files/fits-1.3.0.zip && \
    cd /opt/fits && unzip fits-latest.zip && chmod +X /opt/fits/fits.sh

ENV APP_HOME /home/app/webapp
RUN mkdir $APP_HOME && chown -R app:app /home/app
WORKDIR $APP_HOME

ENV BUNDLE_GEMFILE=$APP_HOME/Gemfile \
  BUNDLE_JOBS=4

COPY --chown=app:app samvera/Gemfile* $APP_HOME/
ENV CFLAGS -Wno-error=format-overflow
RUN /sbin/setuser app bundle install --jobs=4

COPY --chown=app:app samvera $APP_HOME

# Copy configuration overrides to app
COPY --chown=app:app config/ $APP_HOME/config/

RUN mkdir -p $APP_HOME/tmp/cache && chown -R app:app $APP_HOME/tmp
RUN mkdir -p $APP_HOME/public/assets && chown -R app:app $APP_HOME/public/assets

RUN /sbin/setuser app /bin/bash -l -c 'cd /home/app/webapp && (bundle check || bundle install) && DB_ADAPTER=nulldb SECRET_KEY_BASE=dont_care RAILS_ENV=production bundle exec rake assets:precompile'

# reenables pdfs in imagemagick see https://ubuntuforums.org/showthread.php?t=2403266
RUN sed -i '/PDF/s/none/read|write/' /etc/ImageMagick-6/policy.xml

ADD https://time.is/just build-time

# Configure nginx
COPY docker/nginx.sh /etc/service/nginx/run
RUN chmod +x /etc/service/nginx/run
RUN rm -f /etc/service/nginx/down
RUN rm /etc/nginx/sites-enabled/default
COPY docker/webapp.conf /etc/nginx/sites-enabled/webapp.conf
COPY samvera/ops/env.conf /etc/nginx/main.d/env.conf

#RUN /sbin/setuser app bash -l -c "mv ./public/assets ./public/assets-new"

CMD ["/sbin/my_init"]
```

All pretty standard. 

The full output from the Gitlab runner is: 

```Running with gitlab-runner 13.4.0 (4e1f20da)
  on runner-gitlab-runner-cbfdb5d4f-gc6qr AvRjVYC-
Preparing the "kubernetes" executor
00:00
Using Kubernetes namespace: gitlab-managed-apps
Using Kubernetes executor with image gcr.io/kaniko-project/executor:debug-v0.24.0 ...
Preparing environment
00:06
Waiting for pod gitlab-managed-apps/runner-avrjvyc--project-18030565-concurrent-0x8ndj to be running, status is Pending
Waiting for pod gitlab-managed-apps/runner-avrjvyc--project-18030565-concurrent-0x8ndj to be running, status is Pending
Running on runner-avrjvyc--project-18030565-concurrent-0x8ndj via runner-gitlab-runner-cbfdb5d4f-gc6qr...
Getting source from Git repository
00:02
Fetching changes with git depth set to 50...
Initialized empty Git repository in /builds/ubiquitypress/advancinghyku-utils/.git/
Created fresh repository.
Checking out 3f1cca7a as 2.1.0-338...
Skipping Git submodules setup
Downloading artifacts
00:06
Downloading artifacts for scripts (1638304718)...
Downloading artifacts from coordinator... ok        id=1638304718 responseStatus=200 OK token=DXh-oBVB
Downloading artifacts for vanilla (1638304723)...
Downloading artifacts from coordinator... ok        id=1638304723 responseStatus=200 OK token=DtzSrePN
Downloading artifacts for add-plugins (1638304726)...
Downloading artifacts from coordinator... ok        id=1638304726 responseStatus=200 OK token=UnU7FSdE
Executing "step_script" stage of the job script
00:29
$ /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/Dockerfile --destination "eu.gcr.io/$GCLOUD_PROJECT_ID/$IMAGE_NAME:$CI_COMMIT_TAG" --snapshotMode redo
E0930 21:13:21.040901      16 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
INFO[0000] Using dockerignore file: /builds/ubiquitypress/advancinghyku-utils/.dockerignore 
INFO[0000] Retrieving image manifest phusion/passenger-ruby27:1.0.12 
E0930 21:13:21.279926      16 metadata.go:154] while reading 'google-dockercfg' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg
E0930 21:13:21.284207      16 metadata.go:166] while reading 'google-dockercfg-url' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg-url
INFO[0002] Retrieving image manifest phusion/passenger-ruby27:1.0.12 
INFO[0003] Built cross stage deps: map[]                
INFO[0003] Retrieving image manifest phusion/passenger-ruby27:1.0.12 
INFO[0004] Retrieving image manifest phusion/passenger-ruby27:1.0.12 
INFO[0005] Executing 0 build triggers                   
INFO[0005] Unpacking rootfs as cmd RUN apt-get update -qq &&     apt-get install -y                        build-essential                        ghostscript                        imagemagick                        libpq-dev                        nodejs                        libreoffice                        libsasl2-dev                        netcat                        postgresql-client                        rsync                        tzdata                        unzip                        ffmpeg                        &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* requires it. 
INFO[0021] RUN apt-get update -qq &&     apt-get install -y                        build-essential                        ghostscript                        imagemagick                        libpq-dev                        nodejs                        libreoffice                        libsasl2-dev                        netcat                        postgresql-client                        rsync                        tzdata                        unzip                        ffmpeg                        &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 
INFO[0021] Taking snapshot of full filesystem...        
INFO[0025] cmd: /bin/sh                                 
INFO[0025] args: [-c apt-get update -qq &&     apt-get install -y                        build-essential                        ghostscript                        imagemagick                        libpq-dev                        nodejs                        libreoffice                        libsasl2-dev                        netcat                        postgresql-client                        rsync                        tzdata                        unzip                        ffmpeg                        &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*] 
INFO[0025] Running: [/bin/sh -c apt-get update -qq &&     apt-get install -y                        build-essential                        ghostscript                        imagemagick                        libpq-dev                        nodejs                        libreoffice                        libsasl2-dev                        netcat                        postgresql-client                        rsync                        tzdata                        unzip                        ffmpeg                        &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*] 
E: The repository 'https://oss-binaries.phusionpassenger.com/apt/passenger focal Release' does not have a Release file.error building image: error building stage: failed to execute command: waiting for process to exit: exit status 100
ERROR: Job failed: command terminated with exit code 1
```

Are you able to help in anyway? I'm sure we cant be the only ones experiencing issues which are preventing us rolling out code to production. 

Thank you for any help that you can provide and for the time that you have put into this project and the Ruby community. 

Paul.

**Comment by CamJN** [comment] 2021-09-30 21:56
Duplicate of https://github.com/phusion/passenger-docker/issues/322#issuecomment-931713261

**Closed** 2021-10-01 12:24 UTC
